name: angular-first-project

networks:
  default:

volumes:
  node_modules:

services:
  frontend:
    build:
      context: frontend
      target: development-stage
    restart: unless-stopped
    env_file: .env
    networks:
      - default
    volumes:
      - "./frontend/public:/app/public"
      - "./frontend/src:/app/src"
      - "./frontend/angular.json:/app/angular.json"
      - "./frontend/package.json:/app/package.json"
      - "./frontend/package-lock.json:/app/package-lock.json"
      - "./frontend/tsconfig.json:/app/tsconfig.json"
      - "./frontend/tsconfig.app.json:/app/tsconfig.app.json"
      - "./frontend/tsconfig.spec.json:/app/tsconfig.spec.json"
      - "node_modules:/app/node_modules"

  backend:
    build:
      context: backend
      target: development-stage
    restart: unless-stopped
    env_file: .env
    networks:
      - default
    volumes:
      - "./backend:/app"
